### ISSUE TITLE
Nice script but how to install Zabbix on Zimbra ?

### ISSUE THREAD

**Issue by Elf36** [YetOpen/zabbix-scripts#16]
I get this error ?
[root@newmail ~]# systemctl start httpd
Job for httpd.service failed because the control process exited with error code. See "systemctl status httpd.service" and "journalctl -xe" for details.

I  have installed everything according to this

[https://www.zabbix.com/download?zabbix=4.2&os_distribution=centos&os_version=7&db=postgresql](url)

I assume its an HTTPD port issue ?

**Comment by maxxer** [comment]
If you want to install Zabbix server on the same host of Zimbra you will likely need to make httpd listen on a port not used by Zimbra itself.

But it's beyond the scope of this repository, these scripts and templates are just for agent checks.
