### ISSUE TITLE
"value should be a json object"

### ISSUE THREAD

**Issue by miquelangeld** [YetOpen/zabbix-scripts#3]
Hi, first thanks for the script.

I Installed the script, the version is reported to Zabbix but the discovery are not working and I get the error "value should be a json object"

When I execute the script /etc/zabbix/scripts/zbx_zimbra.sh discover  I get:
{
-e      "data":[

{ "{#ZIMBRASERVICE}":"amavis" }, 
{ "{#ZIMBRASERVICE}":"antispam" }, 
{ "{#ZIMBRASERVICE}":"antivirus" }, 
{ "{#ZIMBRASERVICE}":"dnscache" }, 
{ "{#ZIMBRASERVICE}":"memcached" }, 
{ "{#ZIMBRASERVICE}":"mta" }, 
{ "{#ZIMBRASERVICE}":"opendkim" }, 
{ "{#ZIMBRASERVICE}":"proxy" }, 
{ "{#ZIMBRASERVICE}":"snmp" }, 
{ "{#ZIMBRASERVICE}":"stats" }
-e
        ]
}

**Comment by miquelangeld** [comment]
I removed the -e in the json echos
    echo -e "\t\"data\":[\n"
        SRVCS=$($COMMAND status | grep Running | awk '{$(NF--)=""; print}' | sed 's/^/\t{ \"{#ZIMBRASERVICE}\":\"/' | sed 's/\ $/\" },/')
    # Remove last comma from the sting, to make a good JSON
    echo $(echo $SRVCS | sed 's/,+$//')
    echo -e "\n\t]\n"

Now it's working perfectly

**Comment by maxxer** [comment]
Yep I know about this issue, I need to take a look at it :)
