### ISSUE TITLE
Error JSON Discover

### ISSUE THREAD

**Issue by jhonespetter** [YetOpen/zabbix-scripts#6]
Hi,

Discover with error.

**After update:**

```
{
\t"data":[\n
{ "{#ZIMBRASERVICE}":"amavis" }, { "{#ZIMBRASERVICE}":"ldap" }, { "{#ZIMBRASERVICE}":"logger" }, { "{#ZIMBRASERVICE}":"mailbox" }, { "{#ZIMBRASERVICE}":"mta" }, { "{#ZIMBRASERVICE}":"service webapp" }, { "{#ZIMBRASERVICE}":"snmp" }, { "{#ZIMBRASERVICE}":"spell" }, { "{#ZIMBRASERVICE}":"stats" }, { "{#ZIMBRASERVICE}":"zimbra webapp" }, { "{#ZIMBRASERVICE}":"zimbraAdmin webapp" }, { "{#ZIMBRASERVICE}":"zimlet webapp" }, { "{#ZIMBRASERVICE}":"zmconfigd" }
\n\t]\n
}
```

**Before:**

```
{
        "data":[

{ "{#ZIMBRASERVICE}":"amavis" }, { "{#ZIMBRASERVICE}":"ldap" }, { "{#ZIMBRASERVICE}":"logger" }, { "{#ZIMBRASERVICE}":"mailbox" }, { "{#ZIMBRASERVICE}":"mta" }, { "{#ZIMBRASERVICE}":"service webapp" }, { "{#ZIMBRASERVICE}":"snmp" }, { "{#ZIMBRASERVICE}":"spell" }, { "{#ZIMBRASERVICE}":"stats" }, { "{#ZIMBRASERVICE}":"zimbra webapp" }, { "{#ZIMBRASERVICE}":"zimbraAdmin webapp" }, { "{#ZIMBRASERVICE}":"zimlet webapp" }, { "{#ZIMBRASERVICE}":"zmconfigd" }

        ]

}
```

thanks,

Jhones Petter

**Comment by maxxer** [comment]
After _update_ what?

**Comment by maxxer** [comment]
Also, have you tried last version of the script?

**Comment by robbyd2** [comment]
I tried last version with zabbix 3 and I still have "Value should be a JSON object." on discovery :(

**Comment by maxxer** [comment]
What OS type/version are you using?

**Comment by robbyd2** [comment]
Zimbra on ubuntu 14.04.

**Comment by melendur88** [comment]
Thanks for uploading your script. But I have the same problem, but i have' finally found solution. In sh script you have bash function called "fork_discover". This generates a JSON code, but incorretly. You script is good, but when i add to echo"\t\"data\":[\n" and echo "\n\t]\n" a " echo -e " option, this will be work. 
The correct function:

40 fork_discover() {
 41     # Return a list of running services in JSON
 42     SRVCS=$($COMMAND status | grep -v ^Host | awk '{$(NF--)=""; print}' | sed 's/^/\t{ \"{#ZIMBRASERVICE}\":\"/' | sed 's/\ $/\" },/')
 43     echo "{"
 44     echo -e "\t\"data\":[\n"
 45     # Remove last comma from the sting, to make a good JSON
 46     echo $(echo $SRVCS | sed 's/,+$//')
 47     echo -e "\n\t]\n"
 48     echo "}"

**Comment by maxxer** [comment]
how strange, I cannot repro on an Ubuntu14 I have deployed... I've probably _-e_ enabled by default, as it was an upgrade. Anyway [you're right](http://unix.stackexchange.com/a/189819/88439)
