### ISSUE TITLE
network error when retreiving service status

### ISSUE THREAD

**Issue by zzenoxx** [YetOpen/zabbix-scripts#8]
After i installed the scripts on our zimbra server and configured them, i had the following issue: the json file was wrongly parsed to the zabbix server and i fixed the json to a static file.

After this, the services get discovered on the zabbix server but it couldn't retreive all the data. It tries to pull the data through the passive agent, but it keeps generating errors and won't retrieve all the data. From the 18 services it can only find 12 on start from the zabbix agent and it can only sync 4 services

code from the error log on the zabbix server(debug level 3):

`8582:20161105:174049.096 Zabbix agent item "zimbra.status[amavis]" on host "mail.phasehosting.io" failed: first network error, wait for 15 seconds
  8590:20161105:174104.321 resuming Zabbix agent checks on host "mail.phasehosting.io": connection restored`

this keeps repeating every 2 mins, like the item interval is configured.

in zabbix on the latest data following appears(its visible only couple services gets checked):

![zimbraservices](https://cloud.githubusercontent.com/assets/22025543/20031894/76c10ce2-a37f-11e6-9e3e-f88899b9e808.PNG)

I tried changing the pollers and discoverers on the server and agent listerners on the agent to higher values, without effect.I tried changing the timeout value in the zabbix_agentd.d/yo-zimbra.conf file without effect. I also tried to change timeout values in server and agent files but due i am new to zabbix i don't know which has the most effect.

**Comment by zzenoxx** [comment]
Found the solution:

you should add

> Timeout=15

to your zabbix_server.conf or zabbix_proxy.conf.

**Comment by maxxer** [comment]
It's already in [yo-zimbra.conf](https://github.com/YetOpen/zabbix-scripts/blob/master/zabbix-zimbra/yo-zimbra.conf#L5), it should be taken into consideration...
